//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Acorisoft {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class SR {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal SR() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Acorisoft.SR", typeof(SR).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 不能在现存的项目中创建新的项目.
        /// </summary>
        internal static string CannotCreateDatabaseInExitsProject {
            get {
                return ResourceManager.GetString("CannotCreateDatabaseInExitsProject", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 无法反序列化{0}类型的实例.
        /// </summary>
        internal static string CannotDeserializeDocument {
            get {
                return ResourceManager.GetString("CannotDeserializeDocument", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 无法在未打开创作集的情况下初始化集合.
        /// </summary>
        internal static string CannotGetPermission {
            get {
                return ResourceManager.GetString("CannotGetPermission", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 权限检测警告，你错误的调用该方法，已经被阻止.
        /// </summary>
        internal static string CannotInitializeCollection {
            get {
                return ResourceManager.GetString("CannotInitializeCollection", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 无法在未打开创作集的情况下初始化集合.
        /// </summary>
        internal static string CannotInitializeCollectionWithoutOpenCompose {
            get {
                return ResourceManager.GetString("CannotInitializeCollectionWithoutOpenCompose", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 无法序列化{0}类型的实例.
        /// </summary>
        internal static string CannotSerializeDocument {
            get {
                return ResourceManager.GetString("CannotSerializeDocument", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 无法写入属性{0}类型的实例，没有权限.
        /// </summary>
        internal static string CannotSetProperty {
            get {
                return ResourceManager.GetString("CannotSetProperty", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 权限检测警告，你没有足够的权限.
        /// </summary>
        internal static string CannotWrite {
            get {
                return ResourceManager.GetString("CannotWrite", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 无法创建创作集，创建的目标路径为空。.
        /// </summary>
        internal static string DocumentEngine_FolderWasNull {
            get {
                return ResourceManager.GetString("DocumentEngine.FolderWasNull", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 创作集未打开。.
        /// </summary>
        internal static string DocumentEngine_InvalidOperation_ComposeNotOpen {
            get {
                return ResourceManager.GetString("DocumentEngine.InvalidOperation.ComposeNotOpen", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 无法操作，文件未找到。.
        /// </summary>
        internal static string DocumentEngine_InvalidOperation_FileNotFound {
            get {
                return ResourceManager.GetString("DocumentEngine.InvalidOperation.FileNotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 无法重复打开创作集。.
        /// </summary>
        internal static string DocumentEngine_Load_Again {
            get {
                return ResourceManager.GetString("DocumentEngine.Load.Again", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 无法打开创作集，创建的目标路径为空。.
        /// </summary>
        internal static string DocumentEngine_Load_FolderWasNull {
            get {
                return ResourceManager.GetString("DocumentEngine.Load.FolderWasNull", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 无法创建创作集，属性为空。.
        /// </summary>
        internal static string DocumentEngine_PropertyWasNull {
            get {
                return ResourceManager.GetString("DocumentEngine.PropertyWasNull", resourceCulture);
            }
        }
    }
}
