//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Acorisoft.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class SR {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal SR() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Acorisoft.Properties.SR", typeof(SR).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 无名.
        /// </summary>
        internal static string Ability_Empty {
            get {
                return ResourceManager.GetString("Ability.Empty", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 传说.
        /// </summary>
        internal static string Rarity_Five {
            get {
                return ResourceManager.GetString("Rarity.Five", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 史诗.
        /// </summary>
        internal static string Rarity_Four {
            get {
                return ResourceManager.GetString("Rarity.Four", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 普通.
        /// </summary>
        internal static string Rarity_One {
            get {
                return ResourceManager.GetString("Rarity.One", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 传奇.
        /// </summary>
        internal static string Rarity_Three {
            get {
                return ResourceManager.GetString("Rarity.Three", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 优秀.
        /// </summary>
        internal static string Rarity_Two {
            get {
                return ResourceManager.GetString("Rarity.Two", resourceCulture);
            }
        }
    }
}
